import Sidebar from '@/components/ui.custom/sidebar';
import { Provider } from '@radix-ui/react-toast';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900'
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900'
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className='flex min-h-screen'>
					<Sidebar />
					<main className='flex-1 mt-8 p-8 md:ml-64 overflow-y-auto'>
						<Provider>{children}</Provider>
					</main>
				</div>
			</body>
		</html>
	);
}
